import os;

DEFAULT_KALTURA_PATH = "192.168.0.160"
DEFAULT_PARTNER_ID = "99"
DEFAULT_ADMIN_SECRET = "a5c1cb2c9bcd66b825db68533c3ec792"
DEFAULT_SECRET = "8e81fdce8808cbf71b8dc6c8ee258842"
DEFAULT_USER_NAME = "bali@acit.com"
DEFAULT_ACTION_PROFILE_ID = 5

def load_settings(SETTINGS):
    SETTINGS['KALTURA_PATH'] = os.environ.get('KALTURA_PATH', DEFAULT_KALTURA_PATH)
    SETTINGS['PARTNER_ID'] =  int(os.environ.get('PARTNER_ID', DEFAULT_PARTNER_ID))
    SETTINGS['SERVICE_URL'] = "http://" + os.environ.get('KALTURA_PATH', DEFAULT_KALTURA_PATH)
    SETTINGS['ADMIN_SECRET'] = os.environ.get('ADMIN_SECRET', DEFAULT_ADMIN_SECRET)
    SETTINGS['SECRET'] = os.environ.get('SECRET', DEFAULT_SECRET)
    SETTINGS['USER_NAME'] =  os.environ.get('USER_NAME', DEFAULT_USER_NAME)
    SETTINGS['ACTION_PROFILE_ID'] =  os.environ.get('ACTION_PROFILE_ID', DEFAULT_ACTION_PROFILE_ID)
